name: Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    uses: ResilientGroup/MavenSetup/.github/workflows/build.yml@1.7.1
    with:
      javadoc-project-name: JuicyRaspberryPie
    secrets: inherit

  build-python:
    runs-on: ubuntu-latest
    needs: build
    env:
      DOC_STAGING_DIR: target/staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: pip
      - name: Setup Python venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --requirement ./requirements.txt
        working-directory: ./python/mcpi
        shell: bash
      - name: Build documentation
        run: |
          source .venv/bin/activate
          pdoc --html --output-dir ${{ env.DOC_STAGING_DIR }} mcpi
        working-directory: ./python/mcpi
        shell: bash

      - name: Authenticate with Google Cloud
        if: github.ref == 'refs/heads/main'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CLOUDBUILD_COMMON_GCP_KEY }}
      - name: Upload latest Python docs copy to Google Cloud Storage
        if: github.ref == 'refs/heads/main'
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: python/mcpi/${{ env.DOC_STAGING_DIR }}/mcpi
          destination: resilient-reload-javadoc/JuicyRaspberryPie/latest
          process_gcloudignore: false
      - name: Upload versioned Python docs to Google Cloud Storage
        if: needs.build.outputs.release-version != ''
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: python/mcpi/${{ env.DOC_STAGING_DIR }}/mcpi
          destination: resilient-reload-javadoc/JuicyRaspberryPie/${{ needs.build.outputs.release-version }}
          process_gcloudignore: false
